apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: gcp-demo-project
spec:
  selector:
    app: gcp-demo-project
  ports:
    - protocol: "TCP"
      port: 9095 # The port that the service is running on in the cluster
      targetPort: 9095 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.

  
  
---

apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: gcp-demo-project
spec:
  selector:
    matchLabels:
      app: gcp-demo-project
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: gcp-demo-project
    spec:
      containers:
        - name: gcp-demo-project 
          image: ppsinghsingh2/gcp-demo-project:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9095 # The port that the container is running on in the cluster
