replicaCount: 2

image:
  repository: ppsinghsingh2/gcp-demo-project
  pullPolicy: IfNotPresent
  tag: "0.0.2"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: gcp-demo-project-service

service:
  type: ClusterIP
  port: 9095

resources: 
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80